In [14]:
import pandas as pd
import numpy as np

In [15]:
filepath = 'data_test_1.xlsx'
people_data = pd.read_excel(filepath, sheet_name='people_data')
revenue_data = pd.read_excel(filepath, sheet_name='revenue_data')

In [235]:
print("people data: ", people_data.shape)
print("revenue data: ", revenue_data.shape)

people data:  (604, 5)
revenue data:  (5082, 4)

In [17]:
people_data.dtypes

employee_name    object
employee_id       int64
team             object
manager_id        int64
manager_name     object
dtype: object

In [18]:
people_data.isnull().sum()

employee_name    0
employee_id      0
team             0
manager_id       0
manager_name     0
dtype: int64

In [19]:
revenue_data.dtypes

customer_id                    object
customer_close_date    datetime64[ns]
employee_id                     int64
revenue_amount                float64
dtype: object

In [20]:
revenue_data.sample(10)

             customer_id customer_close_date  employee_id  revenue_amount
2164  0061W000010HQ9ZQAV          2020-02-18       170262         1771.54
2188  0061W000010YhStQAK          2020-01-19       180623         7892.68
38    0061W000012p2nHQAQ          2020-01-08       170133         4295.97
3351  0061W00001HY1YmQAI          2020-02-17       170050         2538.50
1135  0061W00001A29GGQA1          2020-02-26       170200          976.04
2914  0061W00001JHYbYQAX          2020-01-07       180361         7437.94
3490  0061W00001KNYjbQAF          2020-02-26       180778         1951.59
4810  0061W00000zW2bLQAQ          2020-02-17       180898         3255.79
436   0061W0000109gQUQA0          2020-03-29       170316         1197.77
171   0061W00001A34LRQAZ          2020-02-29       101045         4357.06

In [22]:
revenue_data.isnull().sum()

customer_id            0
customer_close_date    0
employee_id            0
revenue_amount         0
dtype: int64

In [73]:
people_data.nunique()

employee_name    604
employee_id      597
team              61
manager_id        66
manager_name      66
dtype: int64

In [199]:
# Merge data frames


#df = pd.merge(revenue_data, people_data, on="employee_id", how='right')

df = revenue_data.merge(people_data, on='employee_id', how='left')

In [200]:
df.head()

,customer_id,customer_close_date,employee_id,revenue_amount,employee_name,team,manager_id,manager_name
0,0061W000014nX90QAG,2020-02-16,180534,3966.90,Russell Berkovitz,Sales Engineering - East,192006,Ken Finkelman
1,0061W000011z2eqQAD,2020-01-12,170191,249.72,Thomas Shaw,Business Development - US,170112,Daniel Calloway
2,0061W00001Gx0eCQAQ,2020-01-16,100219,3560.75,Molly Moscati,Business Development - US,180881,Stephanie Orlick
3,0061W00001Ca9msQAA,2020-01-20,100897,8723.86,Raul Zhou,Customer Accounts - East,101252,Ross Bacak
4,0061W000018RWw5QAF,2020-02-15,170024,6911.94,Kevin Khan,Business Development - US,100133,Matthew Quigley

In [201]:
df.shape

(5158, 8)

In [202]:
df.nunique()

customer_id            5080
customer_close_date      91
employee_id             161
revenue_amount         5066
employee_name           163
team                     33
manager_id               41
manager_name             41
dtype: int64

In [145]:
df.sample(200)

,customer_id,customer_close_date,employee_id,revenue_amount,employee_name,team,manager_id,manager_name
5388,NaN,NaT,101206,NaN,Steve Hunt,Strategic Accounts - West,191349,Chris Lesnick
2163,0064000000rGCCVQA5,2020-03-25,101116,7981.38,Eliana Warren,Sales Engineering - East,191754,Kevin Sundaresh
2695,0061W000018zB9BQAV,2020-02-11,180778,6086.23,Kathryn Smith,Wireless - GTM,101252,Ross Bacak
1916,0061W000011upLIQA0,2020-02-15,101236,7079.67,Lance Chandless,Sales Engineering - West,101272,Elliot Nemčić
3305,0061W0000116aeiQAA,2020-03-26,170020,8691.12,Jamie Rice,Business Development - EMEA,191972,Teresa Min
1325,0061W00001EMmxTQAS,2020-02-26,170102,8294.50,Emma Kataoka,Commercial Sales - East,191349,Chris Lesnick
2250,0064000000r8FmFQAW,2020-01-31,100357,6067.69,Bruno Mehta,Customer Accounts - West,192040,Courtney Siverson
1474,0061W00000zecF3QAK,2020-01-04,101045,4350.75,Danielle Suggett,Account Security Sales,191055,Richard Nielsen
3431,0061W000019l2fVQAT,2020-02-29,180377,7893.36,Diana Yamamoto,Mid Market Accounts­ - West,190067,Perry Britchfield
3087,0061W000013R4TWQA0,2020-02-14,170200,1676.69,Doug Kalva,Enterprise Accounts - LATAM,170145,Charlie Oukili
2129,0061W00001HYjm8QAA,2020-01-27,170198,2346.47,Josh Benros,Mid Market Accounts­ - West,191055,Richard Nielsen
5032,0061W00001HRfuRQAS,2020-02-17,191213,6313.60,Sara Lagan,Enterprise Accounts - APAC,191697,Leonardo Schwab
3227,0061W000015iqjoQAB,2020-02-03,190061,768.56,Saad Nouri,Commercial Sales - EMEA,180331,Kevin Staub
2322,0061W000013EHpyQAE,2020-03-14,180609,1166.76,Jennifer Shavers,Enterprise Accounts - West,180331,Kevin Staub
695,0061W00001Ijo9sQAC,2020-01-12,101118,5326.19,Zafar Cousins,CC Specialists - EMEA,100356,Yoshika Chaney
1422,0061W00001BOXDgQAN,2020-02-29,101045,6570.92,Danielle Suggett,Account Security Sales,191055,Richard Nielsen
180,0061W000014pQwDQAW,2020-01-15,100219,5246.06,Molly Moscati,Business Development - US,180881,Stephanie Orlick
1290,0061W000018Qd8KQAT,2020-01-20,170241,238.60,Jimmy Merchant,Customer Accounts - EMEA,101307,Edouard Sharpe
1314,0061W00001A0oUoQAJ,2020-02-21,170102,5249.81,Emma Kataoka,Commercial Sales - East,191349,Chris Lesnick
1680,0061W00001HiySfQAL,2020-02-06,180326,6943.40,Ian Weems,Sales Engineering - East,180331,Kevin Staub
707,0061W000013WhL3QAJ,2020-01-08,170234,3445.06,Aimee Boudreau,Enterprise Accounts - West,170145,Charlie Oukili
2281,0061W0000148sPVQA0,2020-02-19,170284,4996.36,Billy Kennedy,Business Development - US,180583,Andreas Quigley
3351,0061W000017sBypQAE,2020-03-07,101328,7538.38,Timon Huang,Enterprise Accounts - East,191697,Leonardo Schwab
948,0061W00001AjM00QAH,2020-02-26,180339,1776.74,Jimmy Murphy,Commercial Sales - EMEA,170250,Diego Douillard
3789,0061W00001AD1O8QAI,2020-02-28,170262,5010.36,Britt Benros,Enterprise Accounts - West,190039,Amy Rosenboom
5015,0061W00000xBVtAQAX,2020-03-19,190074,2037.20,Jeff Bajwa,Enterprise Accounts - APAC,192040,Courtney Siverson
2038,0061W000019YYQtQAO,2020-03-31,101236,2366.54,Lance Chandless,Sales Engineering - West,101272,Elliot Nemčić
5351,NaN,NaT,191752,NaN,Frankco Holloway,Strategic Accounts - East,170270,Ming-Ming Agarwal
3592,0061W00001248VyQAL,2020-01-13,180833,1698.98,Robert Denham,CC Specialists - NAMER,190768,Jasmin Hoenig
3402,0061W000013VhkqQAA,2020-03-14,170159,2583.55,Damoon Rosenboom,Mid Market Accounts­ - West,180583,Andreas Quigley
...,...,...,...,...,...,...,...,...
1521,0061W000010mTSQQA4,2020-02-01,170064,3155.95,Rebecca Kim,Enterprise Accounts - APAC,101252,Ross Bacak
1939,0061W000014OGCSQA2,2020-03-06,101236,4563.57,Lance Chandless,Sales Engineering - West,101272,Elliot Nemčić
3060,0061W000011VRWGQA2,2020-03-28,170200,2532.31,Doug Kalva,Enterprise Accounts - LATAM,170145,Charlie Oukili
414,0061W000012T7xYQAQ,2020-01-18,170112,8051.15,Daniel Calloway,Twilio.org,190768,Jasmin Hoenig
2088,0061W000012xSfJQAU,2020-01-11,101236,7024.81,Lance Chandless,Sales Engineering - West,101272,Elliot Nemčić
3520,0061W000014jDtiQAH,2020-03-09,180376,3737.74,Yoshika Khan,Sales Engineering - EMEA,191792,Jason Ray
1207,0061W00001IkmTFQA0,2020-01-31,170270,1506.74,Ming-Ming Agarwal,Enterprise Accounts - EMEA,170145,Charlie Oukili
1895,0061W000011qn6iQAB,2020-02-20,180623,3520.12,Alix Clark,Customer Accounts - West,191994,Faisal Han
3055,0061W00000yKR6TQAX,2020-02-17,170200,6774.06,Doug Kalva,Enterprise Accounts - LATAM,170145,Charlie Oukili
797,0061W00001FietPQAQ,2020-02-19,170304,5909.86,Kunal Scott,Sales Engineering - West,170112,Daniel Calloway
5123,0061W00001EkcwwQAC,2020-01-26,180579,6792.20,Jessica Huang,Commercial Sales - East,100687,Eliana Bernard
223,0061W000017tNdOQAV,2020-03-08,100219,4062.46,Molly Moscati,Business Development - US,180881,Stephanie Orlick
1219,0061W00001ASGDnQAM,2020-02-16,170270,4956.97,Ming-Ming Agarwal,Enterprise Accounts - EMEA,170145,Charlie Oukili
3019,0061W00000q7FhvQAE,2020-01-30,100877,8675.21,Futoshi Lombardi,Enterprise Accounts - West,100687,Eliana Bernard
4425,0061W00000yuUzeQAE,2020-02-26,180796,5895.42,Roderick Hoenig,Sales Engineering - West,100133,Matthew Quigley
2555,0061W000019wEhJQAU,2020-01-31,170004,3599.19,Sofien Moore,Mid Market Accounts­ - West,191349,Chris Lesnick
3089,0061W00001KjE8SQAU,2020-02-25,170200,8265.00,Doug Kalva,Enterprise Accounts - LATAM,170145,Charlie Oukili
4855,0061W000019v3eoQAC,2020-03-06,180746,5178.32,Kelli Schmid,Enterprise Accounts - West,180331,Kevin Staub
1854,0061W00001EHkxaQAD,2020-02-06,180623,6422.34,Alix Clark,Customer Accounts - West,191994,Faisal Han
802,0061W00001IoXHxQAO,2020-01-12,170304,1233.41,Kunal Scott,Sales Engineering - West,170112,Daniel Calloway
4321,0061W0000140074QAD,2020-02-06,180772,4313.42,Sarah Pollard,Sales Engineering - East,100133,Matthew Quigley
4385,0061W00001GJpiRQAS,2020-01-08,191148,2887.20,Dirk Shaw,Alliances,100687,Eliana Bernard
829,0061W000010v3y2QAA,2020-02-20,170304,1773.10,Kunal Scott,Sales Engineering - West,170112,Daniel Calloway
1351,0061W00001GfJBtQAM,2020-01-08,170102,969.42,Emma Kataoka,Commercial Sales - East,191349,Chris Lesnick
1618,0061W000011qcicQAB,2020-03-14,170133,5590.21,Alpha Jankauskaite,Commercial Sales - APAC,191055,Richard Nielsen
1163,0061W000017OPx4QAF,2020-01-24,180430,2680.30,Conor Chiazza,Mid Market Accounts -­ APAC,191055,Richard Nielsen
1122,0061W000014Nlz8QAD,2020-03-14,180430,3721.18,Conor Chiazza,Mid Market Accounts -­ APAC,191055,Richard Nielsen
4746,0061W000012TtIPQAY,2020-02-03,191047,4760.83,LaTonya Logan,Mid Market Accounts­ - West,191792,Jason Ray
4398,0061W00001CKdRpQAL,2020-03-30,191062,633.93,David McAllister,Enterprise Accounts - EMEA,100687,Eliana Bernard
518,0061W00001Fx4SkQAJ,2020-02-11,180552,8959.54,Arin Laidlaw,Alliances,200004,Paolo DiLegge

In [203]:
df['month'] = pd.DatetimeIndex(df['customer_close_date']).month

In [204]:
df.sample(50)

,customer_id,customer_close_date,employee_id,revenue_amount,employee_name,team,manager_id,manager_name,month
2372,0061W000012HTmbQAG,2020-02-29,180516,3574.00,Cam Takeda,Enterprise Accounts - West,101307,Edouard Sharpe,2
1573,0061W000016RpSNQAZ,2020-01-04,101266,1165.67,David Farhat,Business Development - US,101307,Edouard Sharpe,1
2161,0061W000018CcI6QAJ,2020-01-03,180542,5419.19,Alicia Robertson,Enterprise Accounts - EMEA,191088,Pathik Heath,1
1484,0061W00001GY4lFQAQ,2020-03-22,180552,8110.06,Arin Laidlaw,Alliances,200004,Paolo DiLegge,3
3357,0061W000010yBiNQAW,2020-02-05,180755,8572.25,Tony Kaye,Sales Engineering - EMEA,180583,Andreas Quigley,2
478,0061W000010qmjAQAQ,2020-03-21,180542,2869.81,Alicia Robertson,Enterprise Accounts - EMEA,191088,Pathik Heath,3
1030,0061W00001FrDjxQAG,2020-03-29,100063,8117.04,Andrew Knutsson,Sales Engineering - EMEA,191064,Nadine Wong,3
69,0061W000017SLMQQA5,2020-03-03,101134,1686.54,Tammy Oluo,Business Development - US,101242,Felicia Pazos,3
4953,0061W000013TcRNQA1,2020-02-21,191643,7076.89,Chris Volas,Sales Engineering - West,101242,Felicia Pazos,2
4147,0061W000014kcA4QAI,2020-02-11,180513,8041.97,Joanne Pilcowitz,Enterprise Accounts - East,170145,Charlie Oukili,2
1246,0061W000015LEnSQAU,2020-01-13,180326,520.27,Ian Weems,Sales Engineering - East,180331,Kevin Staub,1
2209,0061W00001KuhQyQAI,2020-01-31,180430,6238.97,Conor Chiazza,Mid Market Accounts -­ APAC,191055,Richard Nielsen,1
4454,0061W00001BKN1IQAW,2020-03-25,100801,4023.33,Kevin Paul,Strategic Accounts - West,101252,Ross Bacak,3
788,0061W000013RkULQA1,2020-03-21,190061,894.16,Saad Nouri,Commercial Sales - EMEA,180331,Kevin Staub,3
1465,0061W000014ZRApQAM,2020-03-08,101118,4508.11,Zafar Cousins,CC Specialists - EMEA,100356,Yoshika Chaney,3
4340,0061W000012HpYpQAI,2020-02-21,191074,5507.72,Christina Shum,Mgmt & Support - Mid Market Acc,101307,Edouard Sharpe,2
2112,0061W00001GygWMQAZ,2020-01-02,180623,870.25,Alix Clark,Customer Accounts - West,191994,Faisal Han,1
467,0061W000010Ar5KQAS,2020-01-15,170316,4483.20,Jessica Verni,Business Development - US,170145,Charlie Oukili,1
4377,0061W000012YtInQAI,2020-03-18,170170,6267.24,Jahlazha Ben-David,Business Development - US,100687,Eliana Bernard,3
5095,0061W000017S7oFQAS,2020-03-20,180490,7688.53,Futoshi Quincey,Enterprise Accounts - West,170112,Daniel Calloway,3
115,0061W00000yKR6TQAX,2020-02-17,170200,6774.06,Doug Kalva,Enterprise Accounts - LATAM,170145,Charlie Oukili,2
2727,0061W0000112VUyQAO,2020-03-15,180364,1334.99,Robert Stevens,Commercial Sales - EMEA,170145,Charlie Oukili,3
59,0061W00000yNzWtQAI,2020-03-02,100897,2189.83,Raul Zhou,Customer Accounts - East,101252,Ross Bacak,3
916,0061W000015kqkLQAS,2020-01-27,180778,3445.87,Kathryn Smith,Wireless - GTM,101252,Ross Bacak,1
2470,0061W000018YbvdQAA,2020-01-20,170241,5066.21,Jimmy Merchant,Customer Accounts - EMEA,101307,Edouard Sharpe,1
3551,0061W000010qhoQQAQ,2020-03-02,180513,6057.23,Joanne Pilcowitz,Enterprise Accounts - East,170145,Charlie Oukili,3
3890,0061W000012JFgRQAX,2020-01-09,180772,3735.50,Sarah Pollard,Sales Engineering - East,100133,Matthew Quigley,1
3331,0061W00001EdLVxQAO,2020-01-30,180609,7135.16,Jennifer Shavers,Enterprise Accounts - West,180331,Kevin Staub,1
395,0061W000010CAKEQA2,2020-03-10,101118,4039.27,Zafar Cousins,CC Specialists - EMEA,100356,Yoshika Chaney,3
1397,0061W000013jHyMQAW,2020-03-14,100877,7692.71,Futoshi Lombardi,Enterprise Accounts - West,100687,Eliana Bernard,3
4107,0061W000019U3DrQAL,2020-01-27,170102,8302.24,Emma Kataoka,Commercial Sales - East,191349,Chris Lesnick,1
2038,0061W00001AK5ICQA0,2020-01-13,170209,8784.05,Amie Abosi,Alliances,180545,Ryan Caputo,1
1888,0061W000019UQZQQA5,2020-03-07,180542,1082.46,Alicia Robertson,Enterprise Accounts - EMEA,191088,Pathik Heath,3
926,0061W0000116jREQA0,2020-03-16,180778,5314.64,Kathryn Smith,Wireless - GTM,101252,Ross Bacak,3
384,0061W00000zdpp9QAA,2020-03-30,170316,6023.78,Jessica Verni,Business Development - US,170145,Charlie Oukili,3
904,0061W000011oy2pQAB,2020-01-23,170200,5022.10,Doug Kalva,Enterprise Accounts - LATAM,170145,Charlie Oukili,1
2412,0061W00001E55f0QAC,2020-03-06,190018,1246.10,Maria Marler,Enterprise Accounts - West,180583,Andreas Quigley,3
2946,0061W000013D3Y8QAK,2020-02-04,170061,8397.33,Rob Tucker,Business Development - US,101252,Ross Bacak,2
3274,0061W00001EVdFcQAK,2020-02-23,180901,2919.78,Colleen Orahood,Wireless - GTM,100133,Matthew Quigley,2
1152,0061W00000y7ID9QAM,2020-01-10,170004,4253.88,Sofien Moore,Mid Market Accounts­ - West,191349,Chris Lesnick,1
2728,0061W000010lQgXQAU,2020-03-07,101236,3935.44,Lance Chandless,Sales Engineering - West,101272,Elliot Nemčić,3
4928,0061W000015M7aqQAA,2020-02-04,101307,1314.07,Edouard Sharpe,Commercial Sales - West,191349,Chris Lesnick,2
760,0061W00000yj2y5QAC,2020-03-12,180376,2655.60,Yoshika Khan,Sales Engineering - EMEA,191792,Jason Ray,3
4221,0061W00001IrPx4QAF,2020-02-28,180796,4042.32,Roderick Hoenig,Sales Engineering - West,100133,Matthew Quigley,2
1192,0061W0000166LHmQAM,2020-03-01,100897,8579.68,Raul Zhou,Customer Accounts - East,101252,Ross Bacak,3
2546,0061W00001AOB1tQAG,2020-02-04,180635,3535.45,Daniel Meeker,Business Development - US,100480,Jodie Walters,2
2944,0061W000014EryUQAQ,2020-03-04,101236,163.65,Lance Chandless,Sales Engineering - West,101272,Elliot Nemčić,3
1376,0061W000016RU4NQAW,2020-01-22,180552,701.84,Arin Laidlaw,Alliances,200004,Paolo DiLegge,1
3634,0061W00000rH61aQAB,2020-02-23,180833,8954.49,Mark Ou,Enterprise Accounts - West,190768,Jasmin Hoenig,2
377,0061W00001HcNhLQAU,2020-01-24,180778,3969.30,Kathryn Smith,Wireless - GTM,101252,Ross Bacak,1

In [236]:
print("min :", df['customer_close_date'].min())
print("max :", df['customer_close_date'].max())

min : 2020-01-01 00:00:00
max : 2020-03-31 00:00:00

In [206]:
df.shape

(5158, 9)

In [207]:
df = df[df.manager_name != "Eliana Bernard"]

In [208]:
df.shape

(5030, 9)

In [209]:
df.nunique()

customer_id            4952
customer_close_date      91
employee_id             154
revenue_amount         4938
employee_name           156
team                     33
manager_id               40
manager_name             40
month                     3
dtype: int64

In [224]:
df_pivot = pd.pivot_table(data=df, index='team', columns='month', values='revenue_amount', aggfunc='sum')

#pd.pivot_table(data=df_flights, index='year', values='passengers', aggfunc='sum')

In [230]:
print(df_pivot)

month                                    1          2          3
team
Account Security Sales           217104.35  198630.20  131660.04
Alliances                        496679.36  578540.50  575733.30
Business Development - EMEA       76308.83   37968.38  116856.11
Business Development - US        917251.59  837128.89  850337.64
CC Specialists - EMEA             75354.35   91291.06  136308.63
CC Specialists - NAMER           112162.69  111449.46  111394.65
Commercial Sales - APAC           83352.91   58574.96  111815.38
Commercial Sales - EMEA          384870.19  361339.45  434345.74
Commercial Sales - East          186900.52  205876.15  162079.78
Commercial Sales - West          229835.86  172473.22  261351.22
Customer Accounts - EMEA         113317.10   74317.98  121534.94
Customer Accounts - East         217128.60  103402.84  186427.15
Customer Accounts - LATAM         15225.28        NaN    5185.07
Customer Accounts - West         200913.60  190862.29  237821.66
Enterprise Accounts - APAC       167879.06  218402.32  162182.81
Enterprise Accounts - EMEA       288992.45  380702.32  297235.56
Enterprise Accounts - East       340039.78  284789.71  225065.18
Enterprise Accounts - LATAM      112582.04  150707.39  132938.50
Enterprise Accounts - West       822458.70  920690.25  948152.99
Expert Services                   41255.97   17865.99   39329.73
Mgmt & Support - EMEA              2409.31        NaN   10967.60
Mgmt & Support - Mid Market Acc   26258.39   21621.29   32135.91
Mid Market Accounts -­ APAC      158954.23  109035.23  123279.89
Mid Market Accounts­ - West      259766.33  356993.61  346061.63
Sales Development - APAC           4089.51        NaN    3804.28
Sales Engineering - APAC          59793.55   50650.85   43385.61
Sales Engineering - EMEA         129170.77  123858.07  152339.53
Sales Engineering - East         802696.83  632552.56  659274.15
Sales Engineering - West         624488.49  574818.40  677408.04
Strategic Accounts - EMEA          5359.08    8665.11    2603.65
Strategic Accounts - West         81064.96   21311.28   37961.35
Twilio.org                       100403.41   42492.78   83813.21
Wireless - GTM                   429337.26  354595.86  401469.53

In [216]:
df_final = df_pivot[['team', '1', '2', '3']]

KeyError: "['team' '1' '2' '3'] not in index"

In [226]:
df_flattened = pd.DataFrame(df_pivot.to_records())

In [227]:
df_flattened

                               team          1          2          3
0            Account Security Sales  217104.35  198630.20  131660.04
1                         Alliances  496679.36  578540.50  575733.30
2       Business Development - EMEA   76308.83   37968.38  116856.11
3         Business Development - US  917251.59  837128.89  850337.64
4             CC Specialists - EMEA   75354.35   91291.06  136308.63
5            CC Specialists - NAMER  112162.69  111449.46  111394.65
6           Commercial Sales - APAC   83352.91   58574.96  111815.38
7           Commercial Sales - EMEA  384870.19  361339.45  434345.74
8           Commercial Sales - East  186900.52  205876.15  162079.78
9           Commercial Sales - West  229835.86  172473.22  261351.22
10         Customer Accounts - EMEA  113317.10   74317.98  121534.94
11         Customer Accounts - East  217128.60  103402.84  186427.15
12        Customer Accounts - LATAM   15225.28        NaN    5185.07
13         Customer Accounts - West  200913.60  190862.29  237821.66
14       Enterprise Accounts - APAC  167879.06  218402.32  162182.81
15       Enterprise Accounts - EMEA  288992.45  380702.32  297235.56
16       Enterprise Accounts - East  340039.78  284789.71  225065.18
17      Enterprise Accounts - LATAM  112582.04  150707.39  132938.50
18       Enterprise Accounts - West  822458.70  920690.25  948152.99
19                  Expert Services   41255.97   17865.99   39329.73
20            Mgmt & Support - EMEA    2409.31        NaN   10967.60
21  Mgmt & Support - Mid Market Acc   26258.39   21621.29   32135.91
22      Mid Market Accounts -­ APAC  158954.23  109035.23  123279.89
23      Mid Market Accounts­ - West  259766.33  356993.61  346061.63
24         Sales Development - APAC    4089.51        NaN    3804.28
25         Sales Engineering - APAC   59793.55   50650.85   43385.61
26         Sales Engineering - EMEA  129170.77  123858.07  152339.53
27         Sales Engineering - East  802696.83  632552.56  659274.15
28         Sales Engineering - West  624488.49  574818.40  677408.04
29        Strategic Accounts - EMEA    5359.08    8665.11    2603.65
30        Strategic Accounts - West   81064.96   21311.28   37961.35
31                       Twilio.org  100403.41   42492.78   83813.21
32                   Wireless - GTM  429337.26  354595.86  401469.53

In [228]:
df_flattened = df_flattened.fillna(0)

In [229]:
df_flattened['total_revenue'] = df_flattened["1"] + df_flattened["2"] + df_flattened["3"]
df_flattened

,team,1,2,3,total_revenue
0,Account Security Sales,217104.35,198630.20,131660.04,547394.59
1,Alliances,496679.36,578540.50,575733.30,1650953.16
2,Business Development - EMEA,76308.83,37968.38,116856.11,231133.32
3,Business Development - US,917251.59,837128.89,850337.64,2604718.12
4,CC Specialists - EMEA,75354.35,91291.06,136308.63,302954.04
5,CC Specialists - NAMER,112162.69,111449.46,111394.65,335006.80
6,Commercial Sales - APAC,83352.91,58574.96,111815.38,253743.25
7,Commercial Sales - EMEA,384870.19,361339.45,434345.74,1180555.38
8,Commercial Sales - East,186900.52,205876.15,162079.78,554856.45
9,Commercial Sales - West,229835.86,172473.22,261351.22,663660.30
10,Customer Accounts - EMEA,113317.10,74317.98,121534.94,309170.02
11,Customer Accounts - East,217128.60,103402.84,186427.15,506958.59
12,Customer Accounts - LATAM,15225.28,0.00,5185.07,20410.35
13,Customer Accounts - West,200913.60,190862.29,237821.66,629597.55
14,Enterprise Accounts - APAC,167879.06,218402.32,162182.81,548464.19
15,Enterprise Accounts - EMEA,288992.45,380702.32,297235.56,966930.33
16,Enterprise Accounts - East,340039.78,284789.71,225065.18,849894.67
17,Enterprise Accounts - LATAM,112582.04,150707.39,132938.50,396227.93
18,Enterprise Accounts - West,822458.70,920690.25,948152.99,2691301.94
19,Expert Services,41255.97,17865.99,39329.73,98451.69
20,Mgmt & Support - EMEA,2409.31,0.00,10967.60,13376.91
21,Mgmt & Support - Mid Market Acc,26258.39,21621.29,32135.91,80015.59
22,Mid Market Accounts -­ APAC,158954.23,109035.23,123279.89,391269.35
23,Mid Market Accounts­ - West,259766.33,356993.61,346061.63,962821.57
24,Sales Development - APAC,4089.51,0.00,3804.28,7893.79
25,Sales Engineering - APAC,59793.55,50650.85,43385.61,153830.01
26,Sales Engineering - EMEA,129170.77,123858.07,152339.53,405368.37
27,Sales Engineering - East,802696.83,632552.56,659274.15,2094523.54
28,Sales Engineering - West,624488.49,574818.40,677408.04,1876714.93
29,Strategic Accounts - EMEA,5359.08,8665.11,2603.65,16627.84
30,Strategic Accounts - West,81064.96,21311.28,37961.35,140337.59
31,Twilio.org,100403.41,42492.78,83813.21,226709.40
32,Wireless - GTM,429337.26,354595.86,401469.53,1185402.65

In [231]:
df_flattened = df_flattened.rename(columns = {"1": "JAN",
                                             "2": "FEB",
                                             "3": "MAR"})
df_flattened

,team,JAN,FEB,MAR,total_revenue
0,Account Security Sales,217104.35,198630.20,131660.04,547394.59
1,Alliances,496679.36,578540.50,575733.30,1650953.16
2,Business Development - EMEA,76308.83,37968.38,116856.11,231133.32
3,Business Development - US,917251.59,837128.89,850337.64,2604718.12
4,CC Specialists - EMEA,75354.35,91291.06,136308.63,302954.04
5,CC Specialists - NAMER,112162.69,111449.46,111394.65,335006.80
6,Commercial Sales - APAC,83352.91,58574.96,111815.38,253743.25
7,Commercial Sales - EMEA,384870.19,361339.45,434345.74,1180555.38
8,Commercial Sales - East,186900.52,205876.15,162079.78,554856.45
9,Commercial Sales - West,229835.86,172473.22,261351.22,663660.30
10,Customer Accounts - EMEA,113317.10,74317.98,121534.94,309170.02
11,Customer Accounts - East,217128.60,103402.84,186427.15,506958.59
12,Customer Accounts - LATAM,15225.28,0.00,5185.07,20410.35
13,Customer Accounts - West,200913.60,190862.29,237821.66,629597.55
14,Enterprise Accounts - APAC,167879.06,218402.32,162182.81,548464.19
15,Enterprise Accounts - EMEA,288992.45,380702.32,297235.56,966930.33
16,Enterprise Accounts - East,340039.78,284789.71,225065.18,849894.67
17,Enterprise Accounts - LATAM,112582.04,150707.39,132938.50,396227.93
18,Enterprise Accounts - West,822458.70,920690.25,948152.99,2691301.94
19,Expert Services,41255.97,17865.99,39329.73,98451.69
20,Mgmt & Support - EMEA,2409.31,0.00,10967.60,13376.91
21,Mgmt & Support - Mid Market Acc,26258.39,21621.29,32135.91,80015.59
22,Mid Market Accounts -­ APAC,158954.23,109035.23,123279.89,391269.35
23,Mid Market Accounts­ - West,259766.33,356993.61,346061.63,962821.57
24,Sales Development - APAC,4089.51,0.00,3804.28,7893.79
25,Sales Engineering - APAC,59793.55,50650.85,43385.61,153830.01
26,Sales Engineering - EMEA,129170.77,123858.07,152339.53,405368.37
27,Sales Engineering - East,802696.83,632552.56,659274.15,2094523.54
28,Sales Engineering - West,624488.49,574818.40,677408.04,1876714.93
29,Strategic Accounts - EMEA,5359.08,8665.11,2603.65,16627.84
30,Strategic Accounts - West,81064.96,21311.28,37961.35,140337.59
31,Twilio.org,100403.41,42492.78,83813.21,226709.40
32,Wireless - GTM,429337.26,354595.86,401469.53,1185402.65

In [232]:
df_flattened.to_csv('twilio_final.csv', index=False)